### ISSUE TITLE
Cooldown from DM

### ISSUE THREAD

**Issue by Darwin1546** [PlaceholderAPI/Javascript-Expansion#20]
When cooldown runned from DM, it's sending **[Server thread/INFO]: Incorrect usage! /papi help**
Still working tho

```
      requirements:
        cooldown:
          type: string equals
          input: "%javascript_cooldown_1_5%"
          output: "0s"
    left_click_commands:
      - '[console] papi parse %player_name% %javascript_cooldown_1_start%'
```
